#pragma once

#include <limits>
#include <string>
#include <string_view>
#include <cctype>
#include <cstring>
#include <sstream>
#include <fstream>
#include <regex>

// containers
#include <iterator>
#include <set>
#include <unordered_set>
#include <map>
#include <unordered_map>
#include <list>
#include <vector>
#include <tuple>
#include <cstddef>

// utilities
#include <iostream>
#include <cassert>
#include <cmath>
#include <memory>
#include <functional>
#include <algorithm>
#include <utility>
#include <chrono>
#include <random>
#include <thread>
#include <future>
#include <numeric>
#include <functional>
#include <typeindex>
#include <typeinfo>
#include <variant>
#include <any>
#include <filesystem>
#include <system_error>
#include <type_traits>
#include <execution>
